name: build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10
          cache: true

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Zip
        run: zip -r chrome-middle-click-search-${{ github.ref_name }}.zip dist/

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: chrome-middle-click-search-${{ github.ref_name }}.zip
